version: '24.0.7'
services:

        #database Serveer
        database:
            image: mysql:8.0
            ports:
                - 3307:3306
            environment:
                - MYSQL_DATABASE = ${DB_DATABASE}
                - MYSQL_USER = ${DB_USERNAME}
                - MYSQL_PASSWORD = ${DB_PASSWORD}
                - MYSQL_ROOT_PASSWORD = ${DB_PASSWORD}
                - MYSQL_ALLOW_EMPTY_PASSWORD =
            volumes:
                - db-data:/var/lib/mysql


volumes:
    db-data: ~
